### PR TITLE
[DON'T MERGE] reproduce bug

### PR DESCRIPTION
**Pull request by lgarithm**
before:
```
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called after throwing an instance of 'std::runtime_error'
Aborted (core dumped)
```

after:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaFree failed with: 4: driver shutting down
Aborted (core dumped)
```

### CODE REVIEW

**Comment by lgarithm** [comment]
@ganler the detailed cuda error is `4: driver shutting down`


https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038

"
cudaErrorCudartUnloading = 4
This indicates that a CUDA Runtime API call cannot be executed because it is being called during process shut down, at a point in time after CUDA driver has been unloaded.
"

**Comment by ganler** [comment]
@lgarithm I got it. This means we cannot use: RAII + static var + cuda.

I think there're possible 2 fixes:

1. For static storage cuda_tensor, do not call the deleter of the `std::unique_ptr`.
2. Make the cuda tensor in the `find_peak_t` a local var rather than a class member.(What I'm currently doing)

**Comment by ganler** [comment]
@lgarithm 
https://galoisplusplus.coding.me/blog/2018/05/22/cudaErrorCudartUnloading/

This post showed many great solutions. Maybe this can be used in your tensor library to enable a cuda_tensor in static storage.

**Comment by lgarithm** [comment]
@ganler which solution in the blog are you referring to?

**Comment by ganler** [comment]
@lgarithm I think you can add `atexit` in your cuda tensor. Or just ignore it when checking the return value of `cudaFree`.

**Comment by lgarithm** [comment]
@ganler I think 
1). `atexit` should be only used in .cpp files that contains the `main` function.
2). in `openpose-plus`, we should always cleanup our resources before the end of `main`. This can be done in the destructors of various objects, e.g. `~pose_detector_impl()`, `~paf_processor_impl()`, `~peak_finder_t()`

**Comment by ganler** [comment]
@lgarithm 
Fine, I'll handle it in next PR :-)

**Pull request closed without merging**
