### PR TITLE
[WIP] ttl==v0.6.1, std=c++17

### PR DESCRIPTION
**Pull request by lgarithm**
- [ ] use `<ttl/cuda_tensor>`

### CODE REVIEW

**Comment by ganler** [comment]
Well, I think supporting CXX17 may frustrate users who use Ubuntu16.04 where the default gcc5 compiler does not support CXX17(but CXX14 at most). 
Is it possible to lower the standard version while still using the newer `ttl` library?

**Comment by ganler** [comment]
Or we can add a short description helping Ubuntu16.04 users to upgrade their compiler for ppa.

**Comment by lgarithm** [comment]
ttl doesn't require c++17, the only feature that requires c++17 is structural binding, which could 
simplify 

```bash
  const int channel = input.shape().dims()[0];
  const int height = input.shape().dims()[1];
  const int width = input.shape().dims()[2];
```

 to 

```bash
const auto [channel, height, width] = input.dims();
```

I was considering using this feature back in end of 2018, but at that time ubuntu18 was not popolar enough, and cuda driver was not well supported on ubuntu18. Now I think it's time to upgrade to ubuntu18 and we should provide guide to help users upgrade their c++ compilers.

**Comment by ganler** [comment]
> ttl doesn't require c++17, the only feature that requires c++17 is structural binding, which could
> simplify
> 
> ```shell
>   const int channel = input.shape().dims()[0];
>   const int height = input.shape().dims()[1];
>   const int width = input.shape().dims()[2];
> ```
> 
> to
> 
> ```shell
> const auto [channel, height, width] = input.dims();
> ```
> 
> I was considering using this feature back in end of 2018, but at that time ubuntu18 was not popolar enough, and cuda driver was not well supported on ubuntu18. Now I think it's time to upgrade to ubuntu18 and we should provide guide to help users upgrade their c++ compilers.

Cool. I love to be with modern C++ as well. The guidance for Ubuntu users to upgrade gcc5 to gcc7 could be very easy.

- Install gcc7 from ppa.

```shell
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get gcc-7 g++-7
```

- change the default gcc

```shell
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 60
sudo update-alternatives --config gcc
sudo update-alternatives --config g++
```

**Comment by lgarithm** [comment]
@ganler you can manually cherrypick this PR into you master, and then I will close it.
I think this makes merge easier.

Also could you format your code with `clang-format`.
The style is already defined in `.clang-format`, you just need to install the vs-code plugin (https://marketplace.visualstudio.com/items?itemName=xaver.clang-format), it's super convenient.

**Comment by ganler** [comment]
> @ganler you can manually cherrypick this PR into you master, and then I will close it.
> I think this is easier than merge.
> 
> Also could you format your code with `clang-format`.
> The style is already defined in `.clang-format`, you just need to install the vs-code plugin (https://marketplace.visualstudio.com/items?itemName=xaver.clang-format), it's super convenient.

Sure: )

**Pull request closed without merging**
