### PR TITLE
Enabling streaming image processing (pipeline CPU and GPU usages).

### PR DESCRIPTION
**Pull request by lgarithm**

### CODE REVIEW

**Comment by lgarithm** [comment]
gtx 1050ti

```
// inferenced 80 images of 256 x 384, took 2.26s, mean: 28.23ms, FPS: 35.428906, buffer size: 4, use f16: 1, gauss kernel size: 13
} // [main] took 29.37s
// profile info logged to trace.log
        summary of tracer_ctx_t::global (29.370540s)
--------------------------------------------------------------------------------
   count      cumulative (s)               %       mean (ms)    call site
--------------------------------------------------------------------------------
       1           29.370343          100.00      29370.3426    main
       1           26.453556           90.07      26453.5560    create_engine
       1            2.258013            7.69       2258.0128    run
      80            1.811984            6.17         22.6498    operator()
      80            1.624603            5.53         20.3075    execute
      80            1.574883            5.36         19.6860    context->execute
      80            1.293831            4.41         16.1729    get_peak_map
      80            0.664431            2.26          8.3054    same_max_pool_3x3
       1            0.474738            1.62        474.7377    createHandle
      80            0.448909            1.53          5.6114    smooth
     160            0.324501            1.10          2.0281    resize_area
      80            0.190271            0.65          2.3784    operator()::internal
      80            0.174110            0.59          2.1764    select_peaks
      80            0.136639            0.47          1.7080    inplace_select_peaks
      80            0.029290            0.10          0.3661    copy input from host
      80            0.027116            0.09          0.3389    basic_cuda_tensor::fromHost
      80            0.017362            0.06          0.2170    copy output to host
     160            0.015589            0.05          0.0974    basic_cuda_tensor::toHost
      80            0.013598            0.05          0.1700    getAllConnections
      80            0.000567            0.00          0.0071    getHumans
      80            0.000243            0.00          0.0030    generate output
       1            0.000074            0.00          0.0744    createBuffers_
       5            0.000026            0.00          0.0053    basic_cuda_tensor
```

**Comment by lgarithm** [comment]
@luomai streaming can largely improve the throughput. (34 FPS vs 21 FPS)

@zsdonghao streaming doesn't help much on TX2, because same_max_pool_3x3 on CPU of TX2 is too slow.

**Comment by luomai** [comment]
in the 1050 Ti case, we are using both 100% of CPU and GPU?

**Comment by lgarithm** [comment]
TX1

```
// inferenced 80 images of 256 x 384, took 8.05s, mean: 100.66ms, FPS: 9.934759, buffer size: 4, use f16: 1, gauss kernel size: 11
} // [main] took 60.13s
// profile info logged to trace.log
	summary of tracer_ctx_t::global (60.135106s)
--------------------------------------------------------------------------------
   count      cumulative (s)               %       mean (ms)    call site
--------------------------------------------------------------------------------
       1           60.133546          100.00      60133.5457    main
       1           50.324101           83.69      50324.1011    create_engine
       1            8.052496           13.39       8052.4961    run
      80            7.021631           11.68         87.7704    paf_processor_impl::operator()
      80            5.507966            9.16         68.8496    uff_runner_impl::execute
      80            5.375366            8.94         67.1921    get_peak_map
      80            5.319399            8.85         66.4925    uff_runner_impl::context->execute
      80            2.800525            4.66         35.0066    smooth
      80            2.101527            3.49         26.2691    same_max_pool_3x3
       1            1.358847            2.26       1358.8472    createHandle
      80            0.986399            1.64         12.3300    resize heatmap and PAF
     160            0.976152            1.62          6.1009    resize_area
      80            0.651264            1.08          8.1408    paf_processor_impl::operator()::internal
      80            0.585747            0.97          7.3218    find_peak_coords
      80            0.372878            0.62          4.6610    inplace_select_peaks
      80            0.091246            0.15          1.1406    copy output to host
     160            0.079111            0.13          0.4944    basic_cuda_tensor::toHost
      80            0.072543            0.12          0.9068    copy input from host
      80            0.063285            0.11          0.7911    basic_cuda_tensor::fromHost
      80            0.048502            0.08          0.6063    getAllConnections
      80            0.006880            0.01          0.0860    getHumans
      80            0.001217            0.00          0.0152    generate output
       1            0.000488            0.00          0.4882    createBuffers_
       5            0.000090            0.00          0.0180    basic_cuda_tensor
```

**Pull request merged**
